apiVersion: v1
kind: Service
metadata:
  name: scheduling-service
  namespace: whispr-prod
  labels:
    app: scheduling-service
    app.kubernetes.io/name: scheduling-service
spec:
  type: ClusterIP
  selector:
    app: scheduling-service
  ports:
    - name: http
      port: 3013
      targetPort: 3013
      protocol: TCP
    - name: grpc
      port: 50013
      targetPort: 50013
      protocol: TCP
