# https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd

## Custom resource configuration
crds:
  # -- Install and upgrade CRDs
  install: true

####################################################################################################
# High Availabilty mode with autoscaling
####################################################################################################
redis-ha:
  enabled: true

controller:
  replicas: 1

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2

## Globally shared configuration
global:
  # -- Default domain used by all components
  ## Used for ingresses, certificates, SSO, notifications, etc.
  domain: ${ domain }

## Argo Configs
configs:
  cm:
    # Temporary URL (will be updated by the app of apps)
    url: http://localhost:8080

    repositories: |
      - url: https://github.com/whispr-messenger/infrastructure/
        type: git
        name: argocd-apps

    # Minimal RBAC policy
    policy:
      default: role:readonly
      csv: |
        p, role:admin, applications, *, */*, allow
        p, role:admin, clusters, *, *, allow
        p, role:admin, repositories, *, *, allow
        p, role:admin, projects, *, *, allow
        g, argocd-admins, role:admin

  params:
    # Mode insecure for initial setup (to be changed later)
    server.insecure: true
    application.instanceLabelKey: argocd.argoproj.io/instance

  secret:
    argocdServerAdminPassword: ${ admin_password_hash } # bcrypt hash of the admin password



server:
  service:
    type: ClusterIP

  ingress:
    enabled: false # We'll use Istio Gateway

  autoscaling:
    enabled: true
    minReplicas: 2

  metrics:
    enabled: true


