apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: whispr-prod
  labels:
    app: user-service
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/whispr-messenger/user-service/user-service:sha-01c4c8d
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3011
            - name: grpc
              containerPort: 50011
          envFrom:
            - secretRef:
                name: user-service-env
          env:
            - name: DB_SYNCHRONIZE
              value: "false"
            - name: INTERNAL_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: shared-internal-api-token
                  key: INTERNAL_API_TOKEN
            - name: MESSAGING_SERVICE_URL
              value: "http://messaging-service.whispr-prod.svc.cluster.local:4010"
            - name: JWT_ISSUER
              value: "https://auth.whispr.roadmvn.com"
            - name: JWT_AUDIENCE
              value: "whispr-api"
          readinessProbe:
            httpGet:
              path: /user/v1/health/ready
              port: 3011
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /user/v1/health/live
              port: 3011
            initialDelaySeconds: 45
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: whispr-prod
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - name: http
      port: 3011
      targetPort: 3011
      nodePort: 30011
    - name: grpc
      port: 50011
      targetPort: 50011
