apiVersion: v1
kind: Secret
metadata:
  name: jwt-keys
  namespace: whispr-preprod
type: Opaque
stringData:
  jwt_private.pem: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgHsf9dwYN2HGRxFvB
    aU0E3vGek/qB8Tm03A1iZL1bBZ+hRANCAATV FCY2BF5cv+tbNdOMzDWJAqofvtDx
    8xEf8nB4jBejIDAOT/3L2uXhcxmoOGcwvI9SvXkzSZGHdmd2Tz0d1rrc
    -----END PRIVATE KEY-----
  jwt_public.pem: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1RQmNgReXL/rWzXTjMw1iQKqH77Q
    8fMRH/JweIwXoyAwDk/9y9rl4XMZqDhnMLyPUr15M0mRh3Zndk89Hda63A==
    -----END PUBLIC KEY-----
