apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-service-config
  namespace: whispr-prod
  labels:
    app.kubernetes.io/name: messaging-service
data:
  MIX_ENV: "prod"
  PHX_SERVER: "true"
  PHX_HOST: "whispr.fr"
  PORT: "4010"
  GRPC_PORT: "40010"
  LOG_LEVEL: "info"
  POOL_SIZE: "10"
  DB_HOST: "postgresql.postgresql.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "messaging_service_db"
  REDIS_HOST: "redis.redis.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "2"

  # Redis Sentinel Configuration
  REDIS_MODE: "sentinel"
  REDIS_SENTINELS: "redis.redis.svc.cluster.local:26379"
  REDIS_MASTER_NAME: "mymaster"

  # gRPC Services URLs
  SCHEDULING_SERVICE_GRPC_URL: "scheduling-service.whispr-prod.svc.cluster.local:50013"
  AUTH_SERVICE_URL: "grpc://auth-service.whispr-prod.svc.cluster.local:50010"
  USER_SERVICE_URL: "grpc://user-service.whispr-prod.svc.cluster.local:50011"
  MEDIA_SERVICE_URL: "grpc://media-service.whispr-prod.svc.cluster.local:50012"
  NOTIFICATION_SERVICE_URL: "grpc://notification-service.whispr-prod.svc.cluster.local:40011"
