apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: whispr-prod
  labels:
    app: messaging-service
    app.kubernetes.io/name: messaging-service
spec:
  type: ClusterIP
  selector:
    app: messaging-service
  ports:
    - name: http
      port: 4010
      targetPort: 4010
      protocol: TCP
    - name: grpc
      port: 40010
      targetPort: 40010
      protocol: TCP
