---
apiVersion: v1
kind: Service
metadata:
  name: expo-status
  namespace: whispr-preprod
spec:
  type: NodePort
  selector:
    app: expo-status
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30140
