---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: notification-service-app-secret
  namespace: whispr-prod
spec:
  vaultAuthRef: notification-service-vault-auth
  mount: kv
  type: kv-v2
  path: whispr/notification-service/app
  destination:
    name: notification-service-app-secret
    create: true
  refreshAfter: 1h
