apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mobile-web
  name: mobile-web
  namespace: whispr-preprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-web
  template:
    metadata:
      labels:
        app: mobile-web
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - image: ghcr.io/whispr-messenger/mobile-app/mobile-web:sha-47711d8
          imagePullPolicy: Always
          name: mobile-web
          ports:
            - containerPort: 3020
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
          startupProbe:
            httpGet:
              path: /
              port: 3020
            failureThreshold: 30
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: 3020
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3020
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
