apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mobile-web
  name: mobile-web
  namespace: whispr-preprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-web
  template:
    metadata:
      labels:
        app: mobile-web
    spec:
      containers:
        - image: ghcr.io/whispr-messenger/mobile-app/mobile-web:sha-90fa6ee
          imagePullPolicy: Always
          name: mobile-web
          ports:
            - containerPort: 3020
              name: http
