apiVersion: v1
kind: Service
metadata:
  name: mobile-web
  namespace: whispr-preprod
spec:
  type: NodePort
  selector:
    app: mobile-web
  ports:
    - name: http
      port: 3020
      targetPort: 3020
      nodePort: 30130
