apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: whispr-dev
  labels:
    app: messaging-service
    tier: backend
    environment: development
spec:
  type: ClusterIP
  selector:
    app: messaging-service
  ports:
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
