---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whispr-preprod-devzeyu-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/whispr-messenger/infrastructure.git
    targetRevision: zeyu/preprod
    path: argocd-preprod-devzeyu/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
