apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: whispr-dev
  labels:
    app: redis
    tier: infrastructure
    environment: development
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
