apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduling-service
  namespace: whispr-preprod
  labels:
    app: scheduling-service
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduling-service
  template:
    metadata:
      labels:
        app: scheduling-service
    spec:
      containers:
        - name: scheduling-service
          image: ghcr.io/whispr-messenger/scheduling-service/scheduling-service:sha-7a26c08
          ports:
            - name: http
              containerPort: 3013
            - name: grpc
              containerPort: 50013
          envFrom:
            - secretRef:
                name: scheduling-service-env
          env:
            - name: DB_HOST
              value: postgresql.postgresql.svc.cluster.local
            - name: REDIS_HOST
              value: redis-master.redis.svc.cluster.local
            - name: JWT_JWKS_URL
              value: http://auth-service:3010/auth/.well-known/jwks.json
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 384Mi
              cpu: 500m
