apiVersion: v1
kind: Service
metadata:
  name: scheduling-service
  namespace: whispr-preprod
spec:
  type: ClusterIP
  selector:
    app: scheduling-service
  ports:
    - name: http
      port: 3013
      targetPort: 3013
    - name: grpc
      port: 50013
      targetPort: 50013
