# SonarQube configuration for GKE with HTTPS and GitHub OAuth
# Using minimal overrides to avoid conflicts with chart defaults

# Enable SonarQube Community Build
community:
  enabled: true

# Monitoring passcode required by chart 2025.5.0
monitoringPasscode: "whispr-monitoring-2025"

# HTTPS Ingress configuration
ingress:
  enabled: true
  hosts:
    - name: sonarqube.whispr.epitech-msc2026.me
      path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  ingressClassName: nginx
  tls:
    - secretName: sonarqube-tls
      hosts:
        - sonarqube.whispr.epitech-msc2026.me

# GitHub OAuth configuration
sonarProperties:
  sonar.forceAuthentication: "true"
  sonar.auth.github.enabled: "true"
  sonar.auth.github.clientId.secured: "Ov23liyFBsJZ4bBBdixd"
  sonar.auth.github.clientSecret.secured: "240bb9475735bbf6627752a5d19475e111961478"
  sonar.auth.github.organizations: "whispr-messenger"
  sonar.auth.github.allowUsersToSignUp: "true"
  sonar.auth.github.loginStrategy: "Unique"
  sonar.core.serverBaseURL: "https://sonarqube.whispr.epitech-msc2026.me"

# PostgreSQL configuration - minimal overrides
postgresql:
  enabled: true
  auth:
    database: sonarDB
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "standard-rwo"