apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-server-config
  namespace: whispr-preprod
data:
  config.yaml: |
    port: 7880
    bind_addresses:
      - "0.0.0.0"
    log_level: info
    rtc:
      tcp_port: 7881
      use_external_ip: false
      port_range_start: 50000
      port_range_end: 50100
    redis:
      address: redis-master.redis.svc.cluster.local:6379
    turn:
      enabled: false
