apiVersion: v1
kind: Service
metadata:
  name: livekit-server
  namespace: whispr-preprod
spec:
  type: ClusterIP
  selector:
    app: livekit-server
  ports:
    - name: http
      port: 7880
      targetPort: 7880
      protocol: TCP
    - name: rtc-tcp
      port: 7881
      targetPort: 7881
      protocol: TCP
