apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-service
  namespace: whispr-prod
  labels:
    app: moderation-service
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: moderation-service
  template:
    metadata:
      labels:
        app: moderation-service
    spec:
      containers:
        - name: moderation-service
          image: ghcr.io/whispr-messenger/moderation-service:sha-7e4116b
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - secretRef:
                name: moderation-service-env
            - configMapRef:
                name: moderation-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-service
  namespace: whispr-prod
spec:
  type: NodePort
  selector:
    app: moderation-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30014
