apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: whispr-dev
  labels:
    app: media-service
    tier: backend
    environment: development
spec:
  type: ClusterIP
  selector:
    app: media-service
  ports:
    - name: http
      port: 3003
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 50054
      targetPort: grpc
      protocol: TCP
