# Service configuration
service: # -> Kubernetes service that will expose the Gateway
  type: NodePort # -> expose port to all nodes
  ports:
    - name: http2
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
      protocol: TCP

# Resources
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# Autoscaling deactivate for now
autoscaling:
  enabled: false

# Replicas
replicaCount: 1

# Labels
labels:
  app: istio-ingressgateway # Gateway CRD use this label for pod targeting (Kubernetes)
  istio: ingressgateway # Gateway CRD selector (Istio)
