api:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls:
      - hosts:
          - kargo.whispr.epitech.beer
        secretName: kargo-tls
    rules:
      - host: kargo.whispr.epitech.beer
        paths:
          - path: /
            pathType: Prefix
