api:
  host: kargo.whispr.epitech.beer
  adminAccount:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls:
      enabled: true
      selfSignedCert: false
  oidc:
    enabled: true
    issuerURL: https://argocd.whispr.epitech.beer/api/dex
    clientID: kargo
    admins:
      claims:
        groups:
          - whispr-messenger
