apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-config
  namespace: whispr-dev
  labels:
    app: postgres
    environment: development
data:
  init-db.sql: |
    CREATE DATABASE auth_service_db;
    CREATE DATABASE user_service_db;
    CREATE DATABASE media_service_db;
    CREATE DATABASE messaging_service_db;
    CREATE DATABASE notification_service_db;
    CREATE DATABASE scheduling_service_db;
