apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: whispr-preprod
data:
  JWT_ISSUER: "https://auth.whispr.roadmvn.com"
  JWT_AUDIENCE: "whispr-api"
  NOTIFICATION_SERVICE_HOST: "notification-service.whispr-preprod.svc.cluster.local"
  NOTIFICATION_SERVICE_PORT: "4011"
