apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: whispr-preprod
data:
  JWT_JWKS_URL: "http://auth-service.whispr-preprod.svc.cluster.local:3010/auth/.well-known/jwks.json"
  JWT_ISSUER: "https://auth.whispr.roadmvn.com"
  JWT_AUDIENCE: "whispr-api"
  MESSAGING_SERVICE_URL: "http://messaging-service.whispr-preprod.svc.cluster.local:4010"
  MEDIA_SERVICE_URL: "https://preprod-whispr-api.roadmvn.com"
  DB_LOGGING: "false"
