apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: whispr-preprod
  labels:
    app: user-service
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/whispr-messenger/user-service/user-service:sha-3a17519
          ports:
            - name: http
              containerPort: 3011
            - name: grpc
              containerPort: 50011
          envFrom:
            - secretRef:
                name: user-service-env
            - configMapRef:
                name: user-service-config
          env:
            - name: DB_HOST
              value: postgresql.postgresql.svc.cluster.local
            - name: REDIS_HOST
              value: redis-master.redis.svc.cluster.local
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 384Mi
              cpu: 500m
