apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: whispr-prod
  labels:
    istio-injection: enabled  # -> Auto-injection Envoy