---
apiVersion: v1
kind: Namespace
metadata:
  name: whispr-preprod
  labels:
    app.kubernetes.io/part-of: whispr-preprod-devzeyu
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/part-of: whispr-preprod-devzeyu
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    app.kubernetes.io/part-of: whispr-preprod-devzeyu
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    app.kubernetes.io/part-of: whispr-preprod-devzeyu
---
apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube
  labels:
    app.kubernetes.io/part-of: whispr-preprod-devzeyu
