apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: whispr-dev
  labels:
    app: auth-service
    tier: backend
    environment: development
data:
  NODE_ENV: "development"
  HTTP_PORT: "3001"
  GRPC_PORT: "50056"
  DB_TYPE: "postgres"
  DB_HOST: "postgres.whispr-dev.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "auth_service_db"
  DB_MIGRATIONS_RUN: "true"
  DB_SYNCHRONIZE: "false"
  DB_LOGGING: "true"
  REDIS_HOST: "redis.whispr-dev.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_MODE: "direct"
  SWAGGER_ENABLED: "true"
  ENABLE_CORS: "true"
  USER_SERVICE_GRPC_URL: "user-service.whispr-dev.svc.cluster.local:50055"
  MEDIA_SERVICE_GRPC_URL: "media-service.whispr-dev.svc.cluster.local:50054"
  DEMO_MODE: "true"
  OTP_BYPASS_CODE: "000000"
  JWT_ISSUER: "https://auth.whispr.epitech.beer"
  JWT_AUDIENCE: "whispr-api"
