apiVersion: v1
kind: Secret
metadata:
  name: auth-service-jwt-secret
  namespace: whispr-dev
  labels:
    app: auth-service
    environment: development
type: Opaque
stringData:
  jwt_private_key.pem: "placeholder"
  jwt_public_key.pem: "placeholder"
