apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: whispr-dev
  labels:
    app: auth-service
    tier: backend
    environment: development
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 50056
      targetPort: grpc
      protocol: TCP
