apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-autounseal
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://pytoshka.github.io/vault-autounseal
    chart: vault-autounseal
    targetRevision: 0.5.3
    helm:
      parameters:
        - name: settings.vault_url
          value: "http://vault.vault.svc:8200"
        - name: settings.vault_secret_shares
          value: "5"
        - name: settings.vault_secret_threshold
          value: "3"
        - name: settings.namespace
          value: "vault"
        - name: settings.vault_root_token_secret
          value: "vault-root-token"
        - name: settings.vault_keys_secret
          value: "vault-unseal-keys"
        - name: settings.vault_label_selector
          value: "app.kubernetes.io/instance=vault,component=server"
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
