---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3" # After Vault Helm Chart
spec:
  project: infrastructure
  sources:

  # Chart
  - repoURL: https://helm.releases.hashicorp.com
    chart: vault-secrets-operator
    targetRevision: 0.29.1
    helm:
      valueFiles:
        - $values/argocd/helm/vault-secrets-operator/values.yaml

  # Values
  - repoURL: 'https://github.com/whispr-messenger/infrastructure.git'
    targetRevision: main
    ref: values

  # CRs
  - repoURL: 'https://github.com/whispr-messenger/infrastructure.git'
    targetRevision: main
    path: argocd/k8s/vault-secrets-operator

  destination:
    server: https://kubernetes.default.svc
    namespace: vault-secrets-operator-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
