apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-b
  namespace: whispr-prod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  namespace: whispr-prod
  labels:
    app: app-b

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  
  template:
    metadata:
      labels:
        app: app-b
    
    spec:
      serviceAccountName: app-b

      containers:
        - name: app
          image: hashicorp/http-echo:latest
          args:
            - "-text=Hello from App B (Backend) on test-worker"
          ports:
            - containerPort: 5678

---
apiVersion: v1
kind: Service
metadata:
  name: app-b
  namespace: whispr-prod
  labels:
    app: app-b
spec:
  selector:
    app: app-b
  ports:
    - port: 80
      targetPort: 5678
      name: http
