apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: whispr-preprod
data:
  APNS_KEY_PATH: "/etc/apns/AuthKey.p8"
  APNS_KEY_ID: ""
  APNS_TEAM_ID: ""
  APNS_MODE: "dev"
  AUTH_JWKS_URL: "https://whispr-preprod.roadmvn.com/auth/.well-known/jwks.json"
