apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: whispr-preprod
data:
  APNS_KEY_PATH: "/etc/apns/AuthKey.p8"
  APNS_KEY_ID: ""
  APNS_TEAM_ID: ""
  APNS_MODE: "dev"
  APNS_DEFAULT_TOPIC: "com.anonymous.Whispr-Frontend"
  # FCM_PROJECT_ID : remplacer par le project ID Firebase exact (visible dans la console Firebase > Paramètres du projet)
  FCM_PROJECT_ID: "whispr-perso-test"
  FCM_JSON_KEYFILE: "/etc/fcm/keyfile.json"
