apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: whispr-preprod
  labels:
    app: notification-service
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ghcr.io/whispr-messenger/notification-service:sha-73c38f8
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4011
            - name: grpc
              containerPort: 40011
          envFrom:
            - secretRef:
                name: notification-service-env
          env:
            - name: DATABASE_HOST
              value: postgresql.postgresql.svc.cluster.local
            - name: REDIS_HOST
              value: redis-master.redis.svc.cluster.local
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 384Mi
              cpu: 500m
