---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: kargo-vault-auth
  namespace: kargo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: kargo
    serviceAccount: kargo-sa
    audiences:
      - vault
