---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kargo-git-credentials
  namespace: kargo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: kargo-vault-auth
  mount: kv
  type: kv-v2
  path: kargo/git-credentials
  destination:
    name: kargo-git-credentials
    create: true
  refreshAfter: 1h
