---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kargo-github-oauth
  namespace: kargo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: kargo-vault-auth
  mount: kv
  type: kv-v2
  path: kargo/github-oauth
  destination:
    name: kargo-github-oauth
    create: true
  refreshAfter: 1h
