apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  # Ensure that all Kubernetes resources deployed by the application are properly
  # deleted before the Application itself is deleted.
  finalizers:
    - resources-finalizer.argocd.argoproj.io/finalizer
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/whispr-messenger/infrastructure
    targetRevision: main
    path: argocd/applications/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
