apiVersion: v1
kind: Service
metadata:
  name: calls-service
  namespace: whispr-preprod
spec:
  type: NodePort
  selector:
    app: calls-service
  ports:
    - name: http
      port: 4012
      targetPort: 4012
      nodePort: 30122
    - name: grpc
      port: 40012
      targetPort: 40012
      nodePort: 31412
