---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-virtualservice
  namespace: argocd
spec:
  hosts:
  - argocd.whispr.epitech-msc2026.me
  gateways:
  - argocd-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    redirect:
      scheme: https