---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd
spec:
  selector:
    istio: ingressgateway
  servers:
  # HTTP server (no automatic redirect - managed by VirtualService)
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - argocd.whispr.epitech-msc2026.me
  # HTTPS server
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: argocd-cert
    hosts:
    - argocd.whispr.epitech-msc2026.me
