---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-virtualservice
  namespace: argocd
spec:
  hosts:
  - argocd.whispr.epitech-msc2026.me
  gateways:
  - argocd-gateway
  http:
  # Autorise le challenge ACME HTTP-01 sans redirection
  - match:
    - uri:
        prefix: "/.well-known/acme-challenge/"
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
        port:
          number: 80
  # Redirige tout le reste du trafic HTTP vers HTTPS
  - match:
    - uri:
        prefix: "/"
    redirect:
      scheme: https