---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-virtualservice
  namespace: argocd
spec:
  hosts:
  - argocd.whispr.epitech-msc2026.me
  gateways:
  - argocd-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local  # Full FQDN for cross-namespace
        port:
          number: 80
    headers:
      request:
        add:
          x-forwarded-proto: https
          x-forwarded-ssl: "on"