---
# General Argo CD configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Argo CD's externally facing base URL (optional). Required when configuring SSO
  url: https://argocd.whispr.epitech-msc2026.me
  # Enables application status badge feature
  statusbadge.enabled: "true"
  # Enable insecure mode for server (will be terminated by ingress)
  server.insecure: "true"
  # Application instance label key
  application.instanceLabelKey: argocd.argoproj.io/instance
  
  # GitHub OAuth configuration via OIDC
  oidc.config: |
    name: GitHub
    issuer: https://github.com
    clientId: $dex.github.clientId
    clientSecret: $dex.github.clientSecret
    requestedScopes: ["read:user", "user:email", "read:org"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
  
  # Dex configuration for GitHub OAuth
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $dex.github.clientId
        clientSecret: $dex.github.clientSecret
        orgs:
        - name: whispr-messenger
          teams:
          - developers  # You can specify a specific team or remove this to allow all org members