---
# Certificate for ArgoCD
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: istio-ingress # Should match the namespace of the Gateway
spec:
  secretName: argocd-cert  # Matches the credentialName in the Gateway
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - argocd.whispr.epitech-msc2026.me