---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd-vs
  namespace: istio-ingress
spec:
  hosts:
  - argocd.whispr.epitech-msc2026.me
  gateways:
  - argocd/argocd-gateway  # Specify the namespace since VS is in istio-ingress
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local  # Full FQDN for cross-namespace
        port:
          number: 80