apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: whispr-prod
spec:
  type: NodePort
  selector:
    app: media-service
  ports:
    - name: http
      port: 3012
      targetPort: 3012
      nodePort: 30012
    - name: grpc
      port: 50012
      targetPort: 50012
