apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: infrastructure

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  source:
    repoURL: https://github.com/whispr-messenger/infrastructure/
    targetRevision: main
    path: argocd/helm/grafana

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true