---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: opentelemetry-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"

spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      # Chart compatible avec Collector Contrib stable
      targetRevision: 0.104.0
      helm:
        valueFiles:
          - $values/helm/opentelemetry-collector/values.yaml

    - repoURL: "https://github.com/whispr-messenger/infrastructure.git"
      targetRevision: deploy/preprod
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
