---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"

spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      # Pin sur une version Tempo stable compatible Grafana 11
      targetRevision: 1.15.3
      helm:
        valueFiles:
          - $values/helm/tempo/values.yaml

    - repoURL: "https://github.com/whispr-messenger/infrastructure.git"
      targetRevision: deploy/preprod
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
