apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-oauth-secret
  namespace: observability
spec:
  type: kv-v2
  mount: kv
  path: grafana/oauth
  destination:
    name: grafana-oauth-secret
    create: true
  refreshAfter: 1h
  vaultAuthRef: grafana-auth
