apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin-secret
  namespace: observability
spec:
  type: kv-v2
  mount: kv
  path: grafana/admin
  destination:
    name: grafana-admin-secret
    create: true
  refreshAfter: 60s
  vaultAuthRef: grafana-auth
