---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whispr-preprod
  namespace: argocd-preprod
spec:
  project: default
  source:
    repoURL: https://github.com/whispr-messenger/infrastructure.git
    targetRevision: deploy/preprod
    path: argocd-preprod/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
