---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/whispr-messenger/infrastructure
    path: argocd/infrastructure/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}