apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5" # Immediately after Istio control plane
    argocd.argoproj.io/display-name: "Istio Ingress Gateway"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.19.0
    helm:
      releaseName: istio-ingressgateway
      values: |
        service:
          type: LoadBalancer
          annotations:
            cloud.google.com/load-balancer-type: "External"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true