---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/whispr-messenger/infrastructure
    targetRevision: HEAD
    path: k8s/kargo
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
