---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/whispr-messenger/infrastructure
    path: argocd/microservices/
  destination:
    server: https://kubernetes.default.svc