---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preprod-livekit
  namespace: argocd-preprod
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: whispr-app
  sources:
    - repoURL: https://helm.livekit.io
      chart: livekit-server
      targetRevision: 1.7.2
      helm:
        valueFiles:
          - $values/k8s/whispr/preprod/livekit/helm-values.yaml
    - repoURL: https://github.com/whispr-messenger/infrastructure.git
      targetRevision: deploy/preprod
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: whispr-preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preprod-livekit-ingress
  namespace: argocd-preprod
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: whispr-app
  source:
    repoURL: https://github.com/whispr-messenger/infrastructure.git
    targetRevision: deploy/preprod
    path: k8s/whispr/preprod/livekit
    directory:
      include: "ingress.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: whispr-preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
