apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# --> In order ** from first to last **
resources:
  - namespace.yaml
  - service-accounts.yaml
  - peer-authentication.yaml
  - authz-policies.yaml