apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: whispr-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: whispr-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: whispr-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: messaging-service
  namespace: whispr-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: media-service
  namespace: whispr-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: whispr-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: moderation-service
  namespace: whispr-prod