apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vault-vpa
  namespace: vault
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: vault
  updatePolicy:
    updateMode: "Off"
