# ArgoCD Helm Chart values
# Based on argo-cd chart v8.5.2

redis-ha:
  enabled: false

redis:
  enabled: true

global:
  domain: argocd.whispr.epitech.beer

controller:
  replicas: 1

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  service:
    type: ClusterIP
  metrics:
    enabled: true
  ingress:
    enabled: false

applicationSet:
  replicas: 2

crds:
  install: true

dex:
  envFrom:
    - secretRef:
        name: argocd-dex-kargo-client

configs:
  params:
    application.instanceLabelKey: argocd.argoproj.io/instance
    server.insecure: true
  cm:
    url: https://argocd.whispr.epitech.beer
    repositories: |
      - url: https://github.com/whispr-messenger/infrastructure/
        type: git
        name: argocd-apps
    policy:
      default: role:readonly
      csv: |
        p, role:admin, applications, *, */*, allow
        p, role:admin, clusters, *, *, allow
        p, role:admin, repositories, *, *, allow
        p, role:admin, projects, *, *, allow
        g, argocd-admins, role:admin
  secret:
    argocdServerAdminPassword: $2a$10$9Qy2iWAWOh2/MgY6qniJZ.ErnKuI/.rgUv3ptJpgcu4j.KrQmo1hG
