---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devzeyu-backup
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/whispr-messenger/infrastructure.git
    targetRevision: deploy/preprod
    path: k8s/whispr/preprod/backup
    directory:
      recurse: false
      # WHISPR-1069 : le README.md doit être ignoré par ArgoCD (non-Kube YAML)
      exclude: "README.md"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
