---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devzeyu-namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://github.com/whispr-messenger/infrastructure.git
    targetRevision: zeyu/preprod
    path: k8s/whispr/devzeyu/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
