---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devzeyu-sonarqube
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: 2025.1.0+601
    helm:
      releaseName: sonarqube
      values: |
        edition: community
        community:
          enabled: true
        image:
          tag: 25.1-community
          pullPolicy: IfNotPresent
        elasticsearch:
          bootstrapChecks: false
        monitoringPasscode: whispr-preprod-sonar-monitoring
        sonarProperties:
          sonar.web.context: /sonarqube
        OpenShift:
          enabled: false
        postgresql:
          enabled: false
        jdbcOverwrite:
          enabled: true
          jdbcUrl: jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/sonarqube
          jdbcUsername: postgres
          jdbcSecretName: sonarqube-jdbc
          jdbcSecretPasswordKey: password
        prometheusMonitoring:
          podMonitor:
            enabled: false
        prometheusExporter:
          enabled: false
        service:
          type: ClusterIP
        ingress:
          enabled: false
        persistence:
          enabled: true
          size: 10Gi
        initSysctl:
          enabled: true
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 1500m
            memory: 3Gi
        startupProbe:
          initialDelaySeconds: 90
          periodSeconds: 30
          failureThreshold: 30
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 30
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
