apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  # S'assurer que toutes les ressources Kubernetes déployées par l'application sont proprement supprimées avant la suppression de l'Application elle-même.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/whispr-messenger/infrastructure
    targetRevision: main
    path: argocd/applications/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true