apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-service
  namespace: whispr-preprod
  labels:
    app: messaging-service
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-service
  template:
    metadata:
      labels:
        app: messaging-service
    spec:
      containers:
        - name: messaging-service
          image: ghcr.io/whispr-messenger/messaging-service/messaging-service:sha-9d2caed
          ports:
            - name: http
              containerPort: 4010
            - name: grpc
              containerPort: 40010
          envFrom:
            - secretRef:
                name: messaging-service-env
            - configMapRef:
                name: messaging-service-config
          env:
            - name: DATABASE_HOST
              value: postgresql.postgresql.svc.cluster.local
            - name: REDIS_HOST
              value: redis-master.redis.svc.cluster.local
            - name: HTTP_PORT
              value: "4010"
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
