---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # After Istio CRDs, before Istio control plane
    argocd.argoproj.io/display-name: Cert-Manager
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.13.2
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        namespace: cert-manager
        serviceAccount:
          create: true
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
        global:
          leaderElection:
            namespace: cert-manager
        webhook:
          serviceAccount:
            create: true
        cainjector:
          serviceAccount:
            create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m