---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
<<<<<<<< HEAD:argocd/applications/microservices/auth-service.yaml
  name: auth-service
========
  name: scheduling-service
>>>>>>>> main:argocd/applications/scheduling-service.yaml
  namespace: argocd
  labels:
    app.kubernetes.io/name: scheduling-service
    app.kubernetes.io/part-of: whispr
  finalizers:
    - resources-finalizer.argocd.argoproj.io/finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/whispr-messenger/infrastructure
<<<<<<<< HEAD:argocd/applications/microservices/auth-service.yaml
    targetRevision: HEAD
    path: argocd/infrastructure/microservices/auth-service
========
    targetRevision: main
    path: argocd/infrastructure/microservices/scheduling-service
>>>>>>>> main:argocd/applications/scheduling-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: whispr-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
<<<<<<<< HEAD:argocd/applications/microservices/auth-service.yaml
      - ServerSideApply=true
========
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
>>>>>>>> main:argocd/applications/scheduling-service.yaml
