---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scheduling-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/whispr-messenger/infrastructure.git
    targetRevision: main
    path: k8s/whispr/scheduling-service
  destination:
    server: https://kubernetes.default.svc
    namespace: whispr-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m