apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-credentials: 'true'
    nginx.ingress.kubernetes.io/cors-allow-headers: Authorization, Content-Type, Accept,
      Origin, X-Requested-With, X-Device-Type
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, PATCH, DELETE,
      OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: https://whispr-preprod.roadmvn.com
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  name: whispr-preprod-nestjs
  namespace: whispr-preprod
spec:
  ingressClassName: nginx
  rules:
  - host: preprod-whispr-api.roadmvn.com
    http:
      paths:
      - backend:
          service:
            name: auth-service
            port:
              number: 3010
        path: /auth
        pathType: Prefix
      - backend:
          service:
            name: user-service
            port:
              number: 3011
        path: /user
        pathType: Prefix
      - backend:
          service:
            name: media-service
            port:
              number: 3012
        path: /media
        pathType: Prefix
