apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: media-service-s3
  namespace: whispr-prod
spec:
  vaultAuthRef: media-service-vault-auth
  mount: kv
  type: kv-v2
  path: whispr/media-service/s3
  destination:
    name: media-service-s3-secret
    create: true
  refreshAfter: 1h
